site_name: Discrete Simulation Project
site_url: https://vikiru.github.io/discrete-sim/
repo_url: https://github.com/vikiru/discrete-sim
repo_name: discrete-sim

nav:
  - Home: index.md
  - Prerequistes and Setup: setup.md
  - Acknowledgements & License: license.md
  - Running the Simulator & Understanding the Results:
      - Running the Simulator: usage.md
      - Understanding the Results: results.md

theme:
  name: material
  font:
    text: Roboto
  language: en
  features:
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest

  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: cyan
      accent: blue

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
      accent: cyan
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vikiru

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/viskirubakaran/

    - icon: fontawesome/solid/briefcase
      link: https://vikiru.vercel.app/

  analytics:
    provider: google
    property: G-HXXH3ZQ027

copyright: Copyright &copy; 2024 Visakan Kirubakaran

plugins:
  - search
